### PR TITLE
Update from TaycanReporter to EnhancedConsoleTestEngineListener

### PR DESCRIPTION
**Pull request by rezammalik**
- Updated the TaycanReport to the new EnhancedConsoleTestEngineListener.
- Updated to latest kotest version 5.5.5
- Updated base version of plugin to 0.4

image

### CODE REVIEW

**Comment by sksamuel** [comment]
Failing on macos, but otherwise looks good.

**Review by sksamuel — APPROVED** [review]

**Comment by rezammalik** [comment]
Would you be able to do me a favor and publish this? I had to use Java 11 locally to work on this while the repo is 1.8. I didn't want to change it to 11 on the repo too.

**Comment by rezammalik** [comment]
Also if you can go ahead and merge this as I don't have permissions to the base repo. Appreciated.

**Comment by rezammalik** [comment]
I don't see any macosX64Test task for gradle. Was this ever there and got removed somehow? I can try adding it back.

**Comment by rezammalik** [comment]
@sksamuel Whenever you get a chance can you merge and publish this?

**Comment by rezammalik** [comment]
@sksamuel can this be merged in and a new build published? It has been waiting in approved status for quite a bit.

**Comment by Kantis** [comment]
@rezammalik v0.4.0 should be available now (or shortly)

**Pull request merged**
